### ISSUE TITLE
Im Inhaltselement "Nachricht" überlagert ein Feld zwei andere Felder.

### ISSUE THREAD

**Issue by Webstylerin** [heimrichhannot/contao-newselement#2]
Hi,

beim Elementtyp "Nachricht" überlagert das Feld "Meta-Felder" die beiden Felder darüber zur Auswahl des Templates und der Bildgröße. Die überlagerten Felder können so nicht einfach geändert werden.

VG
Nicole

![Bildschirmfoto 2019-09-12 um 08 25 42](https://user-images.githubusercontent.com/3033160/64759500-8d2d8900-d537-11e9-8db9-5934600d571d.png)
![Bildschirmfoto 2019-09-12 um 08 25 49](https://user-images.githubusercontent.com/3033160/64759499-8d2d8900-d537-11e9-852f-42bfe759a09a.png)

**Comment by 365agency** [comment]
Hi, 
Ich hab auf die schnelle eine clr class an das metafield gehangen. Kannst du bitte sagen ob dir das so reicht?
Wurde als 1.1.0 getaggt.

**Comment by Webstylerin** [comment]
Hi,

habe mir gerade die 1.1.0. geholt. Template und Bildgröße lassen sich nun auswählen. Dankeschön!

VG
