### ISSUE TITLE
Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given

### ISSUE THREAD

**Issue by Patric96** [heimrichhannot/contao-newselement#3]
I am using Contao 4.9 and the above Error is thrown when i select the Content Element in the Backend. 
I replaced the argument with an Array (simply added some brackets) and then I was able to create the element and select a message. What's still not working is selecting a template, the input field is empty.

Edit: Deleting the second argument completely fixed it for me

**Comment by koertho** [comment]
@Patric96 Thanks for reporting!
