### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by pointout** [heimrichhannot/contao-newselement#4]
I would like to use this plugin for a Contao installation with php 8. In the composer.json is:
```
"require": {
        "php": "~5.4 || ~7.0",
```
Has somebody testet it for php 8?

**Comment by koertho** [comment]
HI, you could test it with `composer update heimrichhannot/contao-newselement --ignore-platform-reqs` and report back if it works :)

**Comment by pointout** [comment]
It is a managed contao installation. Is there a way to set the flag in Contao Manager? I will try to test it on a local installation.

**Comment by pointout** [comment]
I have a local installation (4.9.24) with this extension and updated the php version from 7.4 to 8.0.15. The plugin is still working. Found no issue so far.

**Comment by koertho** [comment]
Fixed in 1.2.0
